#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Apr  9 16:00:02 2021

@author: kdesousa
"""
import pandas as pd
import numpy as np
def correction(vect2,dt=1/30,dx = 0.022,dy = 0.04,f0=24e9):
    print(vect2)
    theta_rad,phi_rad = vect2[5:7]
    theta_cam,phi_cam = vect2[1:3]
    
    pitch= -12.999994000000001
    yaw = -2.5
    
    lam = 3e8/f0 
    ambphi = lam*180/(dx*np.pi) #32.554420177887685 
    ambtheta = lam*180/(dy*np.pi)#17.904931097838226
    nx = np.rint((phi_cam - phi_rad)/ambphi)
    nz = np.rint((theta_cam - theta_rad)/ambtheta)
   
    phi_rad += (nx)*ambphi
    theta_rad += (nz)*ambtheta
    
    # if np.abs(phi_cam - phi_rad) < ambphi:
    #     phi1 = phi_rad
    #     phi1 += ambphi*np.sign(nx)
    #     if np.abs(phi1 - phi_cam) < np.abs(phi_rad - phi_cam):
    #         phi_rad = phi1
            
    # if np.abs(theta_cam - theta_rad) <ambtheta:
    #     theta1 = theta_rad
    #     theta1 += ambtheta * np.sign(nz)
    #     if np.abs(theta1 - theta_cam)> np.abs(theta_rad - theta_cam):
    #         theta_rad = theta1
    #while( phi_cam - phi_rad > ambphi/2):
    #     phi_rad += ambphi
    # while(theta_cam - theta_rad >ambtheta/2) :
    #     theta_rad += ambtheta
        
    #d,theta,phi,v
   
    vectcor = vect2
    vectcor[5:7] = [theta_rad,phi_rad]
    
    d = vect2[4]
    v = vect2[7]
    # theta1 = vect1[5]
    # theta2 = vect2[5]
    # phi1 = vect1[6]
    # phi2 = vect2[6]
    # vabs = v + d*(theta2 - theta1)/dt + d * np.sin(theta2)* (phi2 - phi1)/dt
    
    vectcor[7]=v / np.cos(phi_rad*np.pi/180)
    
    return vectcor

if __name__ == '__main__':
   dataxee = pd.read_csv('data_est.csv',sep=';').values
   data = pd.read_csv('data.csv')
   
   #z = correction(dataxee[5,:],dataxee[180,:])
   test = [ 6.51918674e+01 , 8.56141457e+01,  1.43202132e+01,  8.32026743e-03,65.1  ,      85.72694267, 78.00401555 ,-7.16075897]
   test1= [ 6.74544044e+01 , 8.58685102e+01, -2.91537442e+01, -3.92323937e+00,68.7  ,      63.19339769 ,83.46988126, -0.16274452]
   test2 = [ 4.87596297e+01 , 8.74149614e+01, -6.42775036e+00,  5.92556768e+00,51.9  ,      78.46304097, 77.08358265 , 6.18429184]
   test3 = [ 1.92914884e+01 , 1.01287032e+02, -2.38916664e+01,  5.80329244e+00,18.9   ,     89.32591646, 76.15974583,  6.18429184]
   test4= [ 6.25340527e+01 , 8.59562474e+01,  1.39324962e+01, -1.19392765e+00,63.6   ,     67.15526127 ,78.92131693 ,-1.4647007]
   
   z = correction(test4)
   print(z)
   