#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Apr  9 16:00:02 2021

@author: kdesousa
"""
import pandas as pd
import numpy as np
def correction(vect2,dt=1/30,dx = 0.022,dy = 0.04,f0=24e9):
    print(vect2)
    theta_rad,phi_rad = vect2[5:7]
    theta_cam,phi_cam = vect2[1:3]
    
    pitch= -12.999994000000001
    yaw = -2.5
    
    lam = 3e8/f0 
    ambphi = lam*180/(dx*np.pi) #32.554420177887685 
    ambtheta = lam*180/(dy*np.pi)#17.904931097838226
    nx = np.rint((phi_cam - phi_rad)/ambphi)
    nz = np.rint((theta_cam - theta_rad)/ambtheta)
   
    phi_rad += (nx)*ambphi
    theta_rad += (nz)*ambtheta
    
    if np.abs(phi_cam - phi_rad) < ambphi:
        phi1 = phi_rad
        phi1 += ambphi*np.sign(nx)
        if np.abs(phi1 - phi_cam) > np.abs(phi_rad - phi_cam):
            phi_rad = phi1
            
    if np.abs(theta_cam - theta_rad) >ambtheta/2:
        theta1 = theta_rad
        theta1 += ambtheta * np.sign(nz)
        if np.abs(theta1 - theta_cam)> np.abs(theta_rad - theta_cam):
            theta_rad = theta1
    #while( phi_cam - phi_rad > ambphi/2):
    #     phi_rad += ambphi
    # while(theta_cam - theta_rad >ambtheta/2) :
    #     theta_rad += ambtheta
        
    #d,theta,phi,v
   
    vectcor = vect2
    vectcor[5:7] = [theta_rad,phi_rad]
    
    d = vect2[4]
    v = vect2[7]
    # theta1 = vect1[5]
    # theta2 = vect2[5]
    # phi1 = vect1[6]
    # phi2 = vect2[6]
    # vabs = v + d*(theta2 - theta1)/dt + d * np.sin(theta2)* (phi2 - phi1)/dt
    
    vectcor[7]=v / np.cos(phi_rad*np.pi/180)
    
    return vectcor

if __name__ == '__main__':
   dataxee = pd.read_csv('data_est.csv',sep=';').values
   data = pd.read_csv('data.csv')
   
   #z = correction(dataxee[5,:],dataxee[180,:])
   
   maybe = [ 50.04259141, 100.18920533,  -9.65049533  , 4.3972918 ,51.9    ,    33.56902489 +2* 32.554420177887685 ,  8.38952386 , 4.55684662]
   may = [34.98588118, 103.98209547, -13.93989234 ,  2.65058119,35.4   ,     61.67256179+ 32.554420177887685 , 11.04428364,  2.76665688]
   fuck = [61.613836,   85.49248376,  8.1430172,  -0.90370174,63.9   ,     65.19016853, 85.27617424, -0.97646713]
   fuck1 = [ 57.3937671,   86.23012005,  10.27473275,   2.78703831,59.4  ,      65.68426083, 86.17744627 , 2.9294014]
   fuck2 = [42.3935702,   88.95974916 , -7.58722981,   0.84080054,44.7  ,     65.19016853, 88.87648134,  0.81372261]
   z = correction(fuck1)
   print(z)
   