#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Apr  9 16:00:02 2021

@author: kdesousa
"""
import pandas as pd
import numpy as np
def correction(vect2,dt=1/30,dx = 0.022,dy = 0.04,f0=24e9):
    print(vect2)
    theta_rad,phi_rad = vect2[5:7]
    theta_cam,phi_cam = vect2[1:3]
    
    pitch= -12.999994000000001
    yaw = -2.5
    
    lam = 3e8/f0 
    ambphi = lam*180/(dx*np.pi) #32.554420177887685 
    ambtheta = lam*180/(dy*np.pi)#17.904931097838226
    nx = np.rint((phi_cam - phi_rad)/ambphi)
    nz = np.rint((theta_cam - theta_rad)/ambtheta)
   
    phi_rad += (nx)*ambphi
    theta_rad += (nz)*ambtheta
    
    # if np.abs(phi_cam - phi_rad) < ambphi:
    #     phi1 = phi_rad
    #     phi1 += ambphi*np.sign(nx)
    #     if np.abs(phi1 - phi_cam) < np.abs(phi_rad - phi_cam):
    #         phi_rad = phi1
            
    # if np.abs(theta_cam - theta_rad) <ambtheta:
    #     theta1 = theta_rad
    #     theta1 += ambtheta * np.sign(nz)
    #     if np.abs(theta1 - theta_cam)> np.abs(theta_rad - theta_cam):
    #         theta_rad = theta1
    #while( phi_cam - phi_rad > ambphi/2):
    #     phi_rad += ambphi
    # while(theta_cam - theta_rad >ambtheta/2) :
    #     theta_rad += ambtheta
        
    #d,theta,phi,v
   
    vectcor = vect2
    vectcor[5:7] = [theta_rad,phi_rad]
    
    d = vect2[4]
    v = vect2[7]
    # theta1 = vect1[5]
    # theta2 = vect2[5]
    # phi1 = vect1[6]
    # phi2 = vect2[6]
    # vabs = v + d*(theta2 - theta1)/dt + d * np.sin(theta2)* (phi2 - phi1)/dt
    
    vectcor[7]=v / np.cos(phi_rad*np.pi/180)
    
    return vectcor

if __name__ == '__main__':
   dataxee = pd.read_csv('data_est.csv',sep=';').values
   data = pd.read_csv('data.csv')
   test= [ 30.99052613, 92.62386709 ,-8.76805152,  5.72071128,32.1  ,     74.44865824, 25.37918252,  6.02154732]
   test1 = [ 69.51930432, 84.33944902, -8.49572002,  4.87020572,73.2  ,      84.27209838, 25.01496208,  5.04508018]
   test2 = [56.9007908 , 85.8920155,  -3.20535181, -2.78865823,60.    ,     85.84774829, 30.80430528 ,-3.09214592 ]
   z = correction(test2)
   
   