#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Feb 16 15:27:38 2021

@author: kdesousa
"""

import numpy as np
import matplotlib.pyplot as plt
x = np.zeros((128,128))
p=1
x[40,50:51]=p
x[41,50]=p
l =np.abs( np.fft.fft2(x))
plt.contourf(l)
plt.colorbar()